import { CustomDecorator, SetMetadata } from '@nestjs/common';

export enum SkippingPolicies {
    AUTOGENERATED_PASSWORD_CHECK = 'AUTOGENERATED_PASSWORD_CHECK',
    STATUS_CHECK = 'STATUS_CHECK'
}

export const AuthGuardSkippingPolicy = (
    policiesToSkip: SkippingPolicies[]
): CustomDecorator<string> => SetMetadata('policiesToSkip', policiesToSkip);

export const SkipStatusCheckCheck = () =>
    SetMetadata('policiesToSkip', [SkippingPolicies.STATUS_CHECK]);
